### ISSUE TITLE
Failed at the node-aead-crypto@1.1.6

### ISSUE THREAD

**Issue by plukieus** [overwatchcorp/tradfri-flux#2]
Hi,

I was just trying to install all required packages on my Raspberry Pi 1 (Model B revision 1.2) but ran into the follow problem:

```
pi@raspberrypi:~/tradfri-flux $ npm install

> node-dtls-client@0.5.4 install /home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client
> node install/postinstall.js

node-dtls-client: testing NodeJS version
  Version < 10, installing node-aead-crypto...
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)

> node-aead-crypto@1.1.6 install /home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto
> node lib/install.js

running rpi1 installation script

> node-aead-crypto@1.1.6 install:rpi1 /home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto
> node-pre-gyp install --build-from-source

node-pre-gyp WARN Using request for node-pre-gyp https download 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo EAI_AGAIN nodejs.org:443
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
gyp ERR! System Linux 4.14.71+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--build-from-source" "--module=/home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm/node_aead_crypto.node" "--module_name=node_aead_crypto" "--module_path=/home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --build-from-source --module=/home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm/node_aead_crypto.node --module_name=node_aead_crypto --module_path=/home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.14.71+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto/node_modules/.bin/node-pre-gyp" "install" "--build-from-source"
node-pre-gyp ERR! cwd /home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --build-from-source --module=/home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm/node_aead_crypto.node --module_name=node_aead_crypto --module_path=/home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto/build/Release/node-v57-linux-arm --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-aead-crypto@1.1.6 install:rpi1: `node-pre-gyp install --build-from-source`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-aead-crypto@1.1.6 install:rpi1 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-28T20_59_33_395Z-debug.log
child_process.js:645
    throw err;
    ^

Error: Command failed: npm run install:rpi1
    at checkExecSyncError (child_process.js:602:13)
    at execSync (child_process.js:642:13)
    at Object.<anonymous> (/home/pi/tradfri-flux/node_modules/node-tradfri-client/node_modules/node-dtls-client/node_modules/node-aead-crypto/lib/install.js:22:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-aead-crypto@1.1.6 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-aead-crypto@1.1.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-28T20_59_41_215Z-debug.log
npm WARN tradfri-test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-dtls-client@0.5.4 install: `node install/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-dtls-client@0.5.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-28T21_00_12_219Z-debug.log
```

Any idea how to fix it?

Thanks for all your work!

**Comment by plukieus** [comment]
npm update two weeks later seamed to fixed it.
